begin;

create table public.expenses (
  id bigint generated by default as identity primary key,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  name text not null check (char_length(trim(name)) > 0),
  category text not null check (category in ('gastosFijos', 'compras', 'gato', 'permitidos')),
  price numeric(12, 2) not null check (price > 0),
  username text not null check (username in ('Edu', 'Janis')),
  date date not null default current_date,
  created_at timestamptz not null default now()
);

create index expenses_owner_created_at_idx
  on public.expenses (owner_id, created_at);

alter table public.expenses enable row level security;

revoke all on table public.expenses from anon;
grant select, insert, update, delete on table public.expenses to authenticated;
grant usage, select on sequence public.expenses_id_seq to authenticated;

create policy "Authenticated users can read their expenses"
  on public.expenses
  for select
  to authenticated
  using ((select auth.uid()) = owner_id);

create policy "Authenticated users can create their expenses"
  on public.expenses
  for insert
  to authenticated
  with check ((select auth.uid()) = owner_id);

create policy "Authenticated users can update their expenses"
  on public.expenses
  for update
  to authenticated
  using ((select auth.uid()) = owner_id)
  with check ((select auth.uid()) = owner_id);

create policy "Authenticated users can delete their expenses"
  on public.expenses
  for delete
  to authenticated
  using ((select auth.uid()) = owner_id);

commit;
